# Generated by Django 4.2 on 2024-07-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(max_length=5000)),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_column='upload_date')),
                ('views', models.IntegerField(default=0)),
                ('adds', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'db_table': 'Cards',
            },
        ),
    ]
